apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-model-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: solllamamodelshare
    readOnly: true
  storageClassName: ""

